/* SingBoxHub Runtime archive container inventory. Rhino ES5 only. */
SBH.versions.runtimeArchiveInventory=2;
(function(){
var P=Packages,F=P.java.io.File,FIS=P.java.io.FileInputStream,BAOS=P.java.io.ByteArrayOutputStream,RA=P.java.lang.reflect.Array,JB=P.java.lang.Byte,JS=P.java.lang.String,MD=P.java.security.MessageDigest,ZF=P.java.util.zip.ZipFile;
var SCHEMA=2,MAX=128,MANMAX=8192,BUF=8192,cacheFile=new F(SBH.paths.cacheDir,"runtime_archive_inventory.json"),cache=SBH.files.readJson(cacheFile,null),cacheKey="";
function pending(state,error){return{schemaVersion:SCHEMA,state:state||"checking",checking:!state||state==="checking",runtimeJarDeclared:false,runtimeJarPath:"",runtimeJarExists:false,runtimeJarCanonicalPathMatched:false,runtimeJarSize:-1,runtimeJarSha256Prefix:"",fileMagicHex:"",containerKind:"unknown",archiveListingAvailable:false,archiveListingTool:"",archiveEntryCount:0,archiveStoredEntryCount:0,archiveListingTruncated:false,archiveUnsafeEntryNameCount:0,archiveEntries:[],entryTypeCounts:{dex:0,classFile:0,jar:0,zip:0,javaSource:0,kotlinSource:0,shellScript:0,json:0,properties:0,manifest:0,nativeLibrary:0,directory:0,other:0},nestedArchiveCandidates:[],executableContentCandidates:[],manifestPresent:false,manifestEntryName:"",manifestBytesRead:0,manifestTruncated:false,manifestKeys:[],manifestSafeFields:[],targetClassesExpectedExternal:false,classLoadingPerformed:false,classInstantiationPerformed:false,socketConnectionAttempted:false,methodInvocationPerformed:false,archiveEntriesExtracted:false,archiveEntriesExecuted:false,temporaryFilesCreated:false,runtimeFilesModified:false,authenticationValueUsed:false,authenticationValueExposed:false,rawEndpointExposed:false,inventoryOnly:true,adapterInvocationEnabled:false,writeOperationsLocked:true,destructiveOperations:false,stale:false,error:error||null,checkedAt:SBH.util.now()};}
function close(x){try{if(x!==null&&x!==undefined)x.close();}catch(e){}}
function jfield(text,key){var m=new RegExp("\\\""+String(key).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"\\\\])*)\\\"").exec(String(text||""));if(!m)return"";try{return String(JSON.parse("\""+m[1]+"\""));}catch(e){return"";}}
function endpoint(){var p=null,t,B=P.android.util.Base64;try{if(SBH.runtime&&typeof SBH.runtime.endpointProbe==="function")p=SBH.runtime.endpointProbe();}catch(e){}if(!p||p.exists!==true||!p.data)return null;try{t=String(new JS(B.decode(String(p.data),B.DEFAULT),"UTF-8"));}catch(e2){return null;}return{runtimeJar:jfield(t,"runtimeJar"),clientClass:jfield(t,"clientClass"),serverClass:jfield(t,"serverClass"),socketName:jfield(t,"socketName"),endpointSize:String(p.size||""),endpointMtime:String(p.mtime||""),endpointSha:String(p.sha||"")};}
function validJar(x){x=String(x||"");return /^\/[A-Za-z0-9_.$+@%:,=~\/-]{1,510}\.jar$/i.test(x)&&x.indexOf("/../")<0&&x.indexOf("//")<0;}
function validClass(x){return /^[A-Za-z_$][A-Za-z0-9_$]*(\.[A-Za-z_$][A-Za-z0-9_$]*)+$/.test(String(x||""));}
function validSocket(x){x=String(x||"");return x.length>0&&x.length<=160&&!/[\r\n\t]/.test(x);}
function evidence(status){var e=endpoint(),i;if(e)return e;i=status?status.runtimeJarStaticInspection:null;if(!i)return null;return{runtimeJar:String(i.runtimeJarPath||""),clientClass:String(i.clientClassName||""),serverClass:String(i.serverClassName||""),socketName:i.socketNameDeclared===true?"declared_socket_name":"",endpointSize:"",endpointMtime:String(i.runtimeJarMtimeEpochSeconds||""),endpointSha:String(i.runtimeJarSha256Prefix||"")};}
function ikey(e){return e?[e.runtimeJar,e.clientClass,e.serverClass,e.endpointSize,e.endpointMtime,e.endpointSha].join("|"):"";}
function canon(f){try{return String(f.getCanonicalPath());}catch(e){return String(f.getAbsolutePath());}}
function inside(root,child){root=String(root||"");child=String(child||"");if(!root||!child)return false;if(child===root)return true;if(root.charAt(root.length-1)!==F.separator)root+=F.separator;return child.indexOf(root)===0;}
function hex(b,n){var a=[],i,v,s,l=Math.min(Number(b.length),Number(n||b.length));for(i=0;i<l;i+=1){v=Number(b[i])&255;s=v.toString(16);a.push(s.length<2?"0"+s:s);}return a.join("");}
function magic(f){var s=null,b=RA.newInstance(JB.TYPE,16),n;try{s=new FIS(f);n=Number(s.read(b));return n>0?hex(b,n):"";}finally{close(s);}}
function sha(f){var s=null,d=MD.getInstance("SHA-256"),b=RA.newInstance(JB.TYPE,BUF),n;try{s=new FIS(f);while((n=Number(s.read(b)))>=0)if(n>0)d.update(b,0,n);return hex(d.digest(),8);}finally{close(s);}}
function uniq(a,v,l){v=String(v||"");var i;if(!v||a.length>=Number(l||64))return;for(i=0;i<a.length;i+=1)if(a[i]===v)return;a.push(v);}
function safeName(x){x=String(x||"").replace(/^\s+|\s+$/g,"");var p,i;if(!x||x.length>240||/^[\\/]/.test(x)||/[\r\n\t\0]/.test(x))return"";p=x.split(/[\\/]/);for(i=0;i<p.length;i+=1)if(p[i]==="..")return"";return x;}
function type(name,dir){var l=String(name||"").toLowerCase();if(dir||/\/$/.test(l))return"directory";if(/(^|\/)meta-inf\/manifest\.mf$/.test(l))return"manifest";if(/\.dex$/.test(l))return"dex";if(/\.class$/.test(l))return"classFile";if(/\.jar$/.test(l))return"jar";if(/\.zip$/.test(l))return"zip";if(/\.java$/.test(l))return"javaSource";if(/\.(kt|kts)$/.test(l))return"kotlinSource";if(/\.(sh|bash)$/.test(l))return"shellScript";if(/\.json$/.test(l))return"json";if(/\.(properties|prop|conf|cfg|ini)$/.test(l))return"properties";if(/\.so$/.test(l))return"nativeLibrary";return"other";}
function add(inv,z){var raw=String(z.getName()||""),name=safeName(raw),t;inv.archiveEntryCount+=1;if(!name){inv.archiveUnsafeEntryNameCount+=1;return;}t=type(name,Boolean(z.isDirectory()));inv.entryTypeCounts[t]=Number(inv.entryTypeCounts[t]||0)+1;if(t==="jar"||t==="zip"||t==="dex")uniq(inv.nestedArchiveCandidates,name,32);if(t==="shellScript"||t==="nativeLibrary")uniq(inv.executableContentCandidates,name,32);if(t==="manifest"&&!inv.manifestEntryName)inv.manifestEntryName=name;if(inv.archiveEntries.length<MAX)inv.archiveEntries.push({name:name,type:t,directory:Boolean(z.isDirectory()),uncompressedSize:Number(z.getSize()),compressedSize:Number(z.getCompressedSize())});}
function readText(zip,e,limit){var s=null,o=new BAOS(),b=RA.newInstance(JB.TYPE,BUF),n,left=Number(limit),w=0,tr=false;try{s=zip.getInputStream(e);while(left>0&&(n=Number(s.read(b,0,Math.min(BUF,left))))>=0){if(n>0){o.write(b,0,n);w+=n;left-=n;}}if(left===0&&Number(s.read())>=0)tr=true;return{text:String(new JS(o.toByteArray(),"UTF-8")),bytes:w,truncated:tr};}finally{close(s);close(o);}}
function manifest(text,inv){var allowed={"Manifest-Version":1,"Main-Class":1,"Created-By":1,"Implementation-Title":1,"Implementation-Version":1,"Specification-Title":1,"Specification-Version":1,"Automatic-Module-Name":1},ls=String(text||"").replace(/\r\n/g,"\n").replace(/\r/g,"\n").split("\n"),rec=[],cur="",i,k,v,p;for(i=0;i<ls.length;i+=1){if(/^ /.test(ls[i])&&cur)cur+=ls[i].substring(1);else{if(cur)rec.push(cur);cur=String(ls[i]||"");}}if(cur)rec.push(cur);for(i=0;i<rec.length;i+=1){p=rec[i].indexOf(":");if(p<=0)continue;k=rec[i].substring(0,p).replace(/^\s+|\s+$/g,"");v=rec[i].substring(p+1).replace(/^\s+|\s+$/g,"");if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/.test(k))continue;uniq(inv.manifestKeys,k,64);if(allowed[k]&&v.length<=160&&!/[\r\n\t\0]/.test(v))inv.manifestSafeFields.push({key:k,value:v});}}
function kind(m){m=String(m||"").toLowerCase();if(m.indexOf("504b0304")===0||m.indexOf("504b0506")===0||m.indexOf("504b0708")===0)return"zip_archive";if(m.indexOf("6465780a")===0)return"raw_dex";if(m.indexOf("cafebabe")===0)return"java_class";if(m.indexOf("7f454c46")===0)return"elf_binary";if(m.indexOf("2321")===0)return"script";return m?"unknown_binary":"unknown";}
function total(c){var k,n=0;for(k in c)if(Object.prototype.hasOwnProperty.call(c,k))n+=Number(c[k]||0);return n;}
function classify(i){var c=i.entryTypeCounts;if(!i.runtimeJarExists)return"runtime_jar_missing";if(!i.runtimeJarCanonicalPathMatched)return"runtime_jar_path_mismatch";if(i.containerKind!=="zip_archive")return"non_zip_container_identified";if(!i.archiveListingAvailable)return"zip_directory_unreadable";if(i.archiveEntryCount===0)return"empty_zip_archive";if(c.dex>0||c.classFile>0)return"class_container_detected";if(i.nestedArchiveCandidates.length>0)return"nested_runtime_archive_detected";if(c.javaSource>0||c.kotlinSource>0)return"source_archive_detected";if(c.shellScript>0||c.nativeLibrary>0)return"executable_payload_archive_detected";if(i.manifestPresent&&total(c)===i.archiveEntryCount&&c.json+c.properties+c.other+c.directory+c.manifest===i.archiveEntryCount)return"metadata_only_archive";return"non_dex_archive_identified";}
function inspectZip(f,inv){var z=null,en,e,me=null,r;try{z=new ZF(f);en=z.entries();while(en.hasMoreElements()){e=en.nextElement();add(inv,e);if(inv.manifestEntryName&&me===null&&String(e.getName())===inv.manifestEntryName)me=e;}inv.archiveListingAvailable=true;inv.archiveListingTool="java.util.zip.ZipFile";inv.archiveStoredEntryCount=inv.archiveEntries.length;inv.archiveListingTruncated=inv.archiveEntryCount>MAX;inv.manifestPresent=inv.entryTypeCounts.manifest>0;if(me!==null){r=readText(z,me,MANMAX);inv.manifestBytesRead=Number(r.bytes||0);inv.manifestTruncated=r.truncated===true;manifest(r.text,inv);}}finally{close(z);}}
function correct(status,e,inv){var d=status?status.protocolDiscovery:null,p=status?status.protocolAdapterPlan:null,ok=e&&validJar(e.runtimeJar)&&validClass(e.clientClass)&&validClass(e.serverClass)&&validSocket(e.socketName),o;if(!ok)return status;if(d&&d.parseOk===true){o=String(d.transportKind||"unknown");d.transportKind="unix_socket";d.transportScore=14;d.transportAmbiguous=false;d.adapterState="transport_identified";d.transportCandidates=[{kind:"unix_socket",score:14},{kind:"shell_cli",score:0}];d.transportCorrection={applied:o!=="unix_socket",originalTransport:o,correctedTransport:"unix_socket",reason:"JAVA_RUNTIME_SOCKET_BOOTSTRAP_FIELDS"};}if(p){o=String(p.selectedTransport||"unknown");p.selectedTransport="unix_socket";p.adapterKind="readonly_unix_socket_status_adapter";p.transportCorrection={applied:o!=="unix_socket",originalTransport:o,correctedTransport:"unix_socket",reason:"JAVA_RUNTIME_SOCKET_BOOTSTRAP_FIELDS"};p.runtimeArchiveInventoryState=inv?String(inv.state||"checking"):"checking";p.adapterInvocationEnabled=false;p.writeOperationsLocked=true;p.destructiveOperations=false;}if(status&&status.writeGate){status.writeGate.protocolTransport="unix_socket";status.writeGate.runtimeArchiveInventory=inv;}return status;}
function persist(i){if(!i||i.checking===true)return;cache=i;cacheKey=String(i.inputKey||"");try{SBH.files.writeJson(cacheFile,i);}catch(e){SBH.log.warn("archive.inventory.cache",SBH.util.errorText(e));}}
function inspect(status,force){var e=evidence(status),key=ikey(e),root=status?String(status.runtimeRoot||""):"",f,real,rr,i;if(!e)return pending(status&&status.checking===true?"checking":"endpoint_evidence_unavailable",null);if(!validJar(e.runtimeJar)){i=pending("runtime_jar_path_invalid","runtimeJar is not a validated absolute JAR path");i.runtimeJarDeclared=!!e.runtimeJar;i.runtimeJarPath=String(e.runtimeJar||"");persist(i);return i;}if(!force&&cache&&cache.stale!==true&&cacheKey===key)return cache;i=pending("non_dex_archive_identified",null);i.checking=false;i.runtimeJarDeclared=true;i.inputKey=key;try{f=new F(String(e.runtimeJar));real=canon(f);rr=root?canon(new F(root)):"";i.runtimeJarPath=real;i.runtimeJarExists=Boolean(f.isFile());i.runtimeJarCanonicalPathMatched=inside(rr,real);i.runtimeJarSize=i.runtimeJarExists?Number(f.length()):-1;if(i.runtimeJarExists){i.fileMagicHex=magic(f);i.containerKind=kind(i.fileMagicHex);i.runtimeJarSha256Prefix=sha(f);if(i.containerKind==="zip_archive"){try{inspectZip(f,i);}catch(ze){i.archiveListingAvailable=false;i.archiveListingTool="java.util.zip.ZipFile";i.error=SBH.util.errorText(ze);}}i.targetClassesExpectedExternal=i.entryTypeCounts.dex===0&&i.entryTypeCounts.classFile===0&&validClass(e.clientClass)&&validClass(e.serverClass);}i.state=classify(i);i.stale=false;i.checkedAt=SBH.util.now();persist(i);return i;}catch(err){i.state="archive_inventory_failed";i.error=SBH.util.errorText(err);i.stale=false;i.checkedAt=SBH.util.now();persist(i);return i;}}
function attach(status,inv){status=status||{};inv=inv||cache||pending("checking",null);status.runtimeArchiveInventory=inv;return correct(status,evidence(status),inv);}
function install(){var r=SBH.runtime,os=r.status,orf=r.refresh,orq=r.request,oas=SBH.app.start;r.status=function(){return attach(os(),cache);};r.refresh=function(){var s=orf(),i=inspect(s,false);return attach(s,i);};r.request=function(q){var c=q&&q.command?String(q.command):"",id=q&&q.requestId?String(q.requestId):"",s,i,x;if(c==="runtime.archive_inventory"){s=orf();i=inspect(s,true);s=attach(s,i);return{ok:i.runtimeJarExists===true&&i.error===null,requestId:id,code:"RUNTIME_ARCHIVE_INVENTORY",stateBefore:s.coreRunning?"running":"stopped",stateAfter:s.coreRunning?"running":"stopped",message:"Runtime 归档封装只读识别完成",data:i};}x=orq(q);try{s=r.status();if(x&&x.data&&s.runtimeArchiveInventory)x.data.runtimeArchiveInventory=s.runtimeArchiveInventory;}catch(e){}return x;};r.archiveInventory=function(){return r.request({requestId:"sbh-archive-inventory-"+SBH.util.now(),command:"runtime.archive_inventory"});};SBH.app.start=function(){var x=oas(),s,i;try{s=r.status();i=s.runtimeArchiveInventory||pending("checking",null);x.runtimeArchiveInventory=String(i.state||"checking");x.runtimeArchiveInventoryDetails=i;if(s.protocolDiscovery){x.runtimeProtocolDiscovery=String(s.protocolDiscovery.state||"checking");x.runtimeProtocolDiscoveryDetails=s.protocolDiscovery;}if(s.protocolAdapterPlan){x.runtimeProtocolAdapterPlan=String(s.protocolAdapterPlan.state||"checking");x.runtimeProtocolAdapterPlanDetails=s.protocolAdapterPlan;}}catch(e){i=pending("archive_inventory_status_unavailable",SBH.util.errorText(e));x.runtimeArchiveInventory=i.state;x.runtimeArchiveInventoryDetails=i;}x.writeOperationsLocked=true;x.destructiveOperations=false;return x;};}
if(!cache||Number(cache.schemaVersion)!==SCHEMA)cache=null;else{cacheKey=String(cache.inputKey||"");cache.stale=true;cache.source="persisted_cache";}
install();
}());
