/* SingBoxHub Runtime DEX main-code contract inspection. Rhino ES5 only. */
SBH.versions.runtimeDexCodeContract=1;
(function(){
var P=Packages,F=P.java.io.File,JS=P.java.lang.String,B64=P.android.util.Base64,SC=P.tornaco.apps.shortx.core.proto.action.ShellCommand;
var V=1,LIM=131072,cacheFile=new F(SBH.paths.cacheDir,"runtime_dex_code_contract.json"),cache=SBH.files.readJson(cacheFile,null),cacheKey="";
function empty(s,e){return{schemaVersion:V,state:s||"checking",checking:!s||s==="checking",runtimeJarDeclared:false,runtimeJarPath:"",runtimeJarExists:false,runtimeJarCanonicalPathMatched:false,runtimeJarSize:-1,runtimeJarSha256Prefix:"",dexPayloadStatus:"not_requested",dexBytesTransferred:0,dexTransferLimitBytes:LIM,dexVersion:"",clientClassName:"",serverClassName:"",clientClassFound:false,serverClassFound:false,clientMainFound:false,serverMainFound:false,clientMainCodeFound:false,serverMainCodeFound:false,clientMain:null,serverMain:null,safeReadOnlyCommandStrings:[],mutatingCommandStrings:[],responseStatusStrings:[],socketApiEvidence:[],streamApiEvidence:[],framingEvidence:[],serializationEvidence:[],authenticationEvidence:[],argumentContractEvidence:[],commandComparisonEvidence:[],correlationEvidence:[],protocolLiteralEvidence:[],commandCarrierState:"unknown",framingState:"unknown",correlationState:"unknown",readOnlyProbeContractReady:false,codeContractEvidenceAvailable:false,classLoadingPerformed:false,classInitializationPerformed:false,classInstantiationPerformed:false,socketConnectionAttempted:false,methodInvocationPerformed:false,dexExecuted:false,temporaryFilesCreated:false,runtimeFilesModified:false,authenticationValueUsed:false,authenticationValueExposed:false,rawDexExposed:false,rawEndpointExposed:false,staticInspectionOnly:true,adapterInvocationEnabled:false,writeOperationsLocked:true,destructiveOperations:false,stale:false,shellExitCode:-1,shellError:"",error:e||null,checkedAt:SBH.util.now()};}
function q(v){return"'"+String(v).replace(/'/g,"'\\''")+"'";}
function cv(d,k){var v=d.get(String(k));return v===null||v===undefined?"":String(v);}
function sh(c){var a=SC.newBuilder().setCommand(String(c)).setSingleShot(true).setId("JS#SingBoxHubRuntimeDexCodeContract").build(),r=shortx.executeAction(a),d;if(!r)throw new Error("shortx.executeAction() returned null");d=r.contextData;if(!d)throw new Error("Shell result.contextData unavailable");return{out:cv(d,"shellOut"),err:cv(d,"shellErr"),code:Number(d.get("shellCode"))};}
function sm(t){var o={},a=String(t||"").split(/\r?\n/),i,p;for(i=0;i<a.length;i+=1){p=a[i].split("\t");if(p.length>1)o[String(p[0])]=String(p.slice(1).join("\t"));}return o;}
function jf(t,k){var m=new RegExp("\\\""+String(k).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"\\\\])*)\\\"").exec(String(t||""));if(!m)return"";try{return String(JSON.parse("\""+m[1]+"\""));}catch(e){return"";}}
function ev(){var p=null,t;try{if(SBH.runtime&&typeof SBH.runtime.endpointProbe==="function")p=SBH.runtime.endpointProbe();}catch(e){}if(!p||p.exists!==true||!p.data)return null;try{t=String(new JS(B64.decode(String(p.data),B64.DEFAULT),"UTF-8"));}catch(e2){return null;}return{jar:jf(t,"runtimeJar"),client:jf(t,"clientClass"),server:jf(t,"serverClass"),size:String(p.size||""),mtime:String(p.mtime||""),sha:String(p.sha||"")};}
function vjar(x){x=String(x||"");return/^\/[A-Za-z0-9_.$+@%:,=~\/-]{1,510}\.jar$/i.test(x)&&x.indexOf("/../")<0&&x.indexOf("//")<0;}
function vcls(x){return/^[A-Za-z_$][A-Za-z0-9_$]*(\.[A-Za-z_$][A-Za-z0-9_$]*)+$/.test(String(x||""));}
function key(e,s){var a=s?s.runtimeArchiveInventory:null,d=s?s.runtimeDexContract:null;return e?[e.jar,e.client,e.server,e.size,e.mtime,e.sha,a?a.runtimeJarSha256Prefix:"",d?d.dexVersion:"",d?d.dexBytesTransferred:""].join("|"):"";}
function cmd(root,e){var a=["T=/system/bin/toybox","J="+q(e.jar),"P="+q(String(root||"")+"/"),"printf 'exists\\t0\\npath\\t0\\nstatus\\tnot_requested\\n'","[ -f \"$J\" ]||exit 0","R=\"$($T readlink -f \"$J\" 2>/dev/null)\"","printf 'exists\\t1\\nreal\\t%s\\n' \"$R\"","case \"$R\" in \"$P\"*) printf 'path\\t1\\n';; *) printf 'status\\tpath_mismatch\\n';exit 0;; esac","printf 'size\\t%s\\n' \"$($T stat -c '%s' \"$J\" 2>/dev/null)\"","S=\"$($T sha256sum \"$J\" 2>/dev/null|$T awk '{print $1}')\"","printf 'sha\\t%s\\n' \"$S\"","U=/system/bin/unzip","[ -x \"$U\" ]||U=\"$T unzip\"","N=\"$($U -p \"$J\" classes.dex 2>/dev/null|$T wc -c|$T tr -d ' \\r\\n')\"","case \"$N\" in ''|*[!0-9]*) printf 'status\\tdex_entry_missing\\n';exit 0;; esac","printf 'dexSize\\t%s\\n' \"$N\"","[ \"$N\" -gt 0 ]||{ printf 'status\\tdex_entry_missing\\n';exit 0;} ","[ \"$N\" -le "+LIM+" ]||{ printf 'status\\toversized\\n';exit 0;} ","D=\"$($U -p \"$J\" classes.dex 2>/dev/null|$T base64|$T tr -d '\\r\\n')\"","[ -n \"$D\" ]||{ printf 'status\\tread_failed\\n';exit 0;} ","printf 'status\\tok\\ndexData\\t%s\\n' \"$D\""];return"/system/bin/toybox timeout 12 /system/bin/sh -c "+q(a.join("\n"));}
function num(v,d){v=Number(v);return isFinite(v)?v:d;}function one(v){return String(v||"0")==="1";}
function bd(b,o,n){o=Number(o);n=Number(n);if(o<0||n<0||o+n>Number(b.length))throw new Error("DEX bounds exceeded");}
function u1(b,o){bd(b,o,1);return Number(b[Number(o)])&255;}function u2(b,o){return u1(b,o)+u1(b,+o+1)*256;}function u4(b,o){return u1(b,o)+u1(b,+o+1)*256+u1(b,+o+2)*65536+u1(b,+o+3)*16777216;}
function ul(b,o){var r=0,s=0,p=+o,v,c=0;do{v=u1(b,p++);r+=(v&127)*Math.pow(2,s);s+=7;if(++c>5)throw new Error("Invalid ULEB128");}while(v&128);return{v:r,p:p};}
function str(b,o){var p=ul(b,o).p,a=[],v;while(p<b.length){v=u1(b,p++);if(v===0)break;if(v<32||v>126)return"";a.push(String.fromCharCode(v));if(a.length>512)throw new Error("DEX string too long");}return a.join("");}
function safe(n,m,l){n=+n;if(n<0||n>m)throw new Error(l+" exceeds limit");return n;}function push(a,v,m){var i;v=String(v||"");if(!v||a.length>=(m||96))return;for(i=0;i<a.length;i+=1)if(a[i]===v)return;a.push(v);}
function desc(n){return"L"+String(n||"").replace(/\./g,"/")+";";}
function pars(b,o,t){var a=[],n,i;if(!o)return a;n=safe(u4(b,o),256,"params");bd(b,+o+4,n*2);for(i=0;i<n;i+=1)a.push(String(t[u2(b,+o+4+i*2)]||"?"));return a;}
function tables(b){var z={},i,o,p,r,sc=safe(u4(b,56),4096,"strings"),so=u4(b,60),tc=safe(u4(b,64),4096,"types"),to=u4(b,68),pc=safe(u4(b,72),2048,"protos"),po=u4(b,76),mc=safe(u4(b,88),8192,"methods"),mo=u4(b,92),cc=safe(u4(b,96),2048,"classes"),co=u4(b,100);z.s=[];z.t=[];z.p=[];z.m=[];z.c={};bd(b,so,sc*4);bd(b,to,tc*4);bd(b,po,pc*12);bd(b,mo,mc*8);bd(b,co,cc*32);for(i=0;i<sc;i+=1)z.s.push(str(b,u4(b,so+i*4)));for(i=0;i<tc;i+=1)z.t.push(String(z.s[u4(b,to+i*4)]||""));for(i=0;i<pc;i+=1){o=po+i*12;p=pars(b,u4(b,o+8),z.t);r=String(z.t[u4(b,o+4)]||"?");z.p.push({r:r,a:p,d:"("+p.join("")+")"+r});}for(i=0;i<mc;i+=1){o=mo+i*8;z.m.push({c:String(z.t[u2(b,o)]||""),n:String(z.s[u4(b,o+4)]||""),p:z.p[u2(b,o+2)]||{r:"?",a:[],d:"(?)?"}});}for(i=0;i<cc;i+=1){o=co+i*32;z.c[String(z.t[u4(b,o)]||"")]={d:u4(b,o+24)};}return z;}
function skipf(b,p,n){var i,x;for(i=0;i<n;i+=1){x=ul(b,p);p=x.p;x=ul(b,p);p=x.p;}return p;}
function methods(b,o,t){var a=[],p=+o,x,sf,inf,dm,vm,idx=0,af,co,i;if(!p)return a;x=ul(b,p);sf=safe(x.v,1024,"sf");p=x.p;x=ul(b,p);inf=safe(x.v,1024,"if");p=x.p;x=ul(b,p);dm=safe(x.v,1024,"dm");p=x.p;x=ul(b,p);vm=safe(x.v,1024,"vm");p=x.p;p=skipf(b,p,sf);p=skipf(b,p,inf);function part(n){var j,d;idx=0;for(j=0;j<n;j+=1){x=ul(b,p);d=x.v;p=x.p;idx+=d;x=ul(b,p);af=x.v;p=x.p;x=ul(b,p);co=x.v;p=x.p;a.push({i:idx,a:af,o:co,r:t.m[idx]});}}part(dm);part(vm);return a;}
function width(b,io,pc){var x=u2(b,io+pc*2),op=x&255,id,n,ew,ec;if(op===0){id=x>>>8;if(id===1){n=u2(b,io+(pc+1)*2);return 4+n*2;}if(id===2){n=u2(b,io+(pc+1)*2);return 2+n*4;}if(id===3){ew=u2(b,io+(pc+1)*2);ec=u4(b,io+(pc+2)*2);return 4+Math.ceil(ew*ec/2);}return 1;}if(op===0x18)return 5;if(op===3||op===6||op===9||op===0x14||op===0x17||op===0x1b||(op>=0x24&&op<=0x26)||(op>=0x2a&&op<=0x2c)||(op>=0x6e&&op<=0x72)||(op>=0x74&&op<=0x78)||op===0xee||op===0xef||op===0xf0||op===0xf8||op===0xf9||op===0xfc||op===0xfd)return 3;if(op===0xfa||op===0xfb)return 4;if(op===2||op===5||op===8||op===0x13||op===0x15||op===0x16||op===0x19||op===0x1a||op===0x1c||op===0x1f||op===0x20||op===0x22||op===0x23||(op>=0x2d&&op<=0x3d)||(op>=0x44&&op<=0x6d)||(op>=0x90&&op<=0xaf)||(op>=0xd0&&op<=0xeb)||op===0xed||(op>=0xf2&&op<=0xf7)||op===0xfe||op===0xff)return 2;return 1;}
function lit(v){v=String(v||"");if(!v||v.length>120||/[\r\n\t\0]/.test(v)||/^[A-Fa-f0-9]{24,}$/.test(v)||/^[A-Za-z0-9+/=_-]{32,}$/.test(v))return"";return v;}
function rv(r,i){var v=r[String(i)];if(!v)return"v"+i;if(v.k==="s")return"string:"+v.v;if(v.k==="i")return"int:"+v.v;if(v.k==="a")return"arg["+v.v+"]";if(v.k==="args")return"mainArgs";if(v.k==="ret")return"return:"+v.v;return v.k+":"+(v.v||"");}
function regs(x,y,range){var a=[],n,i;if(range!==null){n=x>>>8;for(i=0;i<n&&i<32;i+=1)a.push(range+i);return a;}n=(x>>>8)&15;if(n>0)a.push(y&15);if(n>1)a.push((y>>>4)&15);if(n>2)a.push((y>>>8)&15);if(n>3)a.push(y>>>12);if(n>4)a.push(x>>>12);return a;}
function code(b,e,t,role){var o=+e.o,rs=u2(b,o),ins=u2(b,o+2),outs=u2(b,o+4),sz=u4(b,o+12),io=o+16,pc=0,w,x,y,op,A,B,C,idx,m,rr,args=[],st={},last=null,s={role:role,registersSize:rs,insSize:ins,outsSize:outs,insnsSize:sz,instructionCount:0,constStrings:[],invokedMethods:[],referencedTypes:[],argumentAccesses:[],commandComparisons:[],arrayLengthChecks:[],truncated:false},i,v,l,r,sg;bd(b,io,sz*2);if((e.a&8)&&ins>0)st[String(rs-ins)]={k:"args"};while(pc<sz){if(s.instructionCount++>512){s.truncated=true;break;}x=u2(b,io+pc*2);op=x&255;w=width(b,io,pc);if(w<1||pc+w>sz)throw new Error("Bad instruction width");if(op===7){A=(x>>>8)&15;B=x>>>12;st[A]=st[B]||null;}else if(op===8){A=x>>>8;B=u2(b,io+(pc+1)*2);st[A]=st[B]||null;}else if(op===9){A=u2(b,io+(pc+1)*2);B=u2(b,io+(pc+2)*2);st[A]=st[B]||null;}else if(op===0x0c&&last){A=x>>>8;st[A]={k:"ret",v:last};}else if(op===0x12){A=(x>>>8)&15;v=x>>>12;st[A]={k:"i",v:(v&8)?v-16:v};}else if(op===0x13){A=x>>>8;v=u2(b,io+(pc+1)*2);st[A]={k:"i",v:(v&32768)?v-65536:v};}else if(op===0x14){A=x>>>8;st[A]={k:"i",v:u2(b,io+(pc+1)*2)|(u2(b,io+(pc+2)*2)<<16)};}else if(op===0x1a||op===0x1b){A=x>>>8;idx=op===0x1a?u2(b,io+(pc+1)*2):u4(b,io+(pc+1)*2);v=lit(t.s[idx]);if(v){st[A]={k:"s",v:v};push(s.constStrings,v);}}else if(op===0x1c||op===0x1f||op===0x22){idx=u2(b,io+(pc+1)*2);push(s.referencedTypes,t.t[idx]);if(op===0x22)st[x>>>8]={k:"t",v:t.t[idx]};}else if(op===0x21){A=(x>>>8)&15;B=x>>>12;if(st[B]&&st[B].k==="args"){st[A]={k:"len"};push(s.arrayLengthChecks,"mainArgs.length->v"+A);}}else if(op===0x46){A=x>>>8;y=u2(b,io+(pc+1)*2);B=y&255;C=y>>>8;if(st[B]&&st[B].k==="args"&&st[C]&&st[C].k==="i"){st[A]={k:"a",v:st[C].v};sg="arg["+st[C].v+"]->v"+A;push(s.argumentAccesses,sg);}}else if((op>=0x6e&&op<=0x72)||(op>=0x74&&op<=0x78)){idx=u2(b,io+(pc+1)*2);y=u2(b,io+(pc+2)*2);m=t.m[idx];if(m){rr=regs(x,y,op>=0x74?y:null);args=[];for(i=0;i<rr.length;i+=1)args.push(rv(st,rr[i]));sg=m.c+"->"+m.n+m.p.d;push(s.invokedMethods,sg);last=sg;if(/Ljava\/lang\/String;->(equals|equalsIgnoreCase|startsWith|endsWith|contains)\(/.test(sg)&&args.length>1){l=args[0];r=args[1];if((l.indexOf("arg[")===0&&r.indexOf("string:")===0)||(r.indexOf("arg[")===0&&l.indexOf("string:")===0))push(s.commandComparisons,m.n+"("+l+","+r+")");}}}pc+=w;}return s;}
function main(b,t,d){var c=t.c[d],a,i;if(!c)return{cf:false,mf:false,m:null};a=methods(b,c.d,t);for(i=0;i<a.length;i+=1)if(a[i].r&&a[i].r.n==="main"&&a[i].r.p.d==="([Ljava/lang/String;)V")return{cf:true,mf:true,m:a[i]};return{cf:true,mf:false,m:null};}
function merge(r,s){var i,v;for(i=0;i<s.constStrings.length;i+=1){v=s.constStrings[i];if(/^(PING|STATUS)$/i.test(v))push(r.safeReadOnlyCommandStrings,v.toUpperCase());if(/^(START|STOP_CORE|STOP_RUNTIME|RESTART|RELOAD)$/i.test(v))push(r.mutatingCommandStrings,v.toUpperCase());if(/^(ALREADY_STOPPED|ERROR|RUNTIME_STOPPING|STARTED|STOPPED|RUNNING|OK|PONG)$/i.test(v))push(r.responseStatusStrings,v.toUpperCase());if(/token|auth|credential|secret/i.test(v))push(r.authenticationEvidence,"literal:"+v);if(/request.?id|correlation|message.?id|sequence|transaction.?id|nonce/i.test(v))push(r.correlationEvidence,"literal:"+v);if(/ping|status|start|stop|runtime|core|error|result|message|command|action|socket|token|json/i.test(v))push(r.protocolLiteralEvidence,v);}for(i=0;i<s.invokedMethods.length;i+=1){v=s.invokedMethods[i];if(/Landroid\/net\/LocalSocket;|Landroid\/net\/LocalSocketAddress;/.test(v))push(r.socketApiEvidence,v);if(/InputStream|OutputStream|Reader|Writer|BufferedReader|BufferedWriter|PrintWriter|DataInputStream|DataOutputStream/.test(v))push(r.streamApiEvidence,v);if(/readLine|println|writeUTF|readUTF|writeInt|readInt|->write\(|->read\(|flush/.test(v))push(r.framingEvidence,v);if(/JSONObject|JSONArray|Gson|JsonReader|JsonWriter|org\/json/.test(v))push(r.serializationEvidence,v);if(/token|auth|credential|secret/i.test(v))push(r.authenticationEvidence,"method:"+v);}for(i=0;i<s.argumentAccesses.length;i+=1)push(r.argumentContractEvidence,s.role+":"+s.argumentAccesses[i]);for(i=0;i<s.commandComparisons.length;i+=1)push(r.commandComparisonEvidence,s.role+":"+s.commandComparisons[i]);}
function decode(b,e,r){var mg="",i,fs=u4(b,32),hs=u4(b,36),t,c,s,v;for(i=0;i<8;i+=1)mg+=String.fromCharCode(u1(b,i));if(mg.substring(0,4)!=="dex\n"||u1(b,7)!==0)throw new Error("Invalid DEX magic");r.dexVersion=mg.substring(4,7);if(fs!==Number(b.length)||hs<112)throw new Error("Invalid DEX header");t=tables(b);c=main(b,t,desc(e.client));s=main(b,t,desc(e.server));r.clientClassFound=c.cf;r.serverClassFound=s.cf;r.clientMainFound=c.mf;r.serverMainFound=s.mf;if(c.m&&c.m.o){r.clientMain=code(b,c.m,t,"client");r.clientMainCodeFound=true;merge(r,r.clientMain);}if(s.m&&s.m.o){r.serverMain=code(b,s.m,t,"server");r.serverMainCodeFound=true;merge(r,r.serverMain);}r.codeContractEvidenceAvailable=r.clientMainCodeFound&&r.serverMainCodeFound;r.commandCarrierState=r.commandComparisonEvidence.length?"main_arguments_and_command_comparisons_identified":(r.argumentContractEvidence.length?"main_argument_access_identified":(r.protocolLiteralEvidence.length?"protocol_literals_identified_without_argument_mapping":"unknown"));v=r.framingEvidence.join("\n");r.framingState=/readLine|println/.test(v)?"line_delimited_text_candidate":(/readUTF|writeUTF/.test(v)?"modified_utf_length_frame_candidate":(/readInt|writeInt/.test(v)?"integer_length_frame_candidate":(r.streamApiEvidence.length?"stream_io_identified_framing_unknown":"unknown")));r.correlationState=r.correlationEvidence.length?"explicit_correlation_evidence_identified":"no_explicit_correlation_evidence";r.readOnlyProbeContractReady=r.codeContractEvidenceAvailable&&r.safeReadOnlyCommandStrings.length>0&&r.socketApiEvidence.length>0&&r.framingState!=="unknown"&&r.authenticationEvidence.length>0;r.state=r.codeContractEvidenceAvailable?"main_code_contract_identified":((r.clientMainCodeFound||r.serverMainCodeFound)?"partial_main_code_contract_identified":((r.clientMainFound||r.serverMainFound)?"main_methods_without_code":((r.clientClassFound||r.serverClassFound)?"target_classes_without_main":"target_classes_not_found")));}
function save(r){if(!r||r.checking)return;cache=r;cacheKey=String(r.inputKey||"");try{SBH.files.writeJson(cacheFile,r);}catch(e){SBH.log.warn("dex.code.contract.cache",SBH.util.errorText(e));}}
function inspect(st,force){var e=ev(),k=key(e,st),root=st?String(st.runtimeRoot||""):"",r,x,m,b;if(!e)return empty(st&&st.checking?"checking":"endpoint_evidence_unavailable",null);if(!vjar(e.jar)||!vcls(e.client)||!vcls(e.server)){r=empty("dex_code_evidence_invalid","invalid endpoint evidence");r.inputKey=k;save(r);return r;}if(!force&&cache&&!cache.stale&&cacheKey===k)return cache;r=empty("dex_code_inspection_failed",null);r.checking=false;r.runtimeJarDeclared=true;r.runtimeJarPath=e.jar;r.clientClassName=e.client;r.serverClassName=e.server;r.inputKey=k;try{x=sh(cmd(root,e));m=sm(x.out);r.shellExitCode=x.code;r.shellError=x.err;r.runtimeJarExists=one(m.exists);r.runtimeJarCanonicalPathMatched=one(m.path);r.runtimeJarPath=m.real||e.jar;r.runtimeJarSize=num(m.size,-1);r.runtimeJarSha256Prefix=String(m.sha||"").substring(0,16);r.dexPayloadStatus=m.status||"unknown";r.dexBytesTransferred=num(m.dexSize,0);if(!r.runtimeJarExists)r.state="runtime_jar_missing";else if(!r.runtimeJarCanonicalPathMatched)r.state="runtime_jar_path_mismatch";else if(r.dexPayloadStatus!=="ok"||!m.dexData)r.state="dex_payload_unavailable";else{b=B64.decode(String(m.dexData),B64.DEFAULT);r.dexBytesTransferred=Number(b.length);decode(b,e,r);}r.stale=false;r.checkedAt=SBH.util.now();save(r);return r;}catch(err){r.state="dex_code_parse_failed";r.error=SBH.util.errorText(err);r.stale=false;r.checkedAt=SBH.util.now();save(r);return r;}}
function attach(st,c){var p;st=st||{};c=c||cache||empty("checking",null);st.runtimeDexCodeContract=c;p=st.protocolAdapterPlan;if(p){p.runtimeDexCodeContractState=c.state;p.codeContractEvidenceAvailable=c.codeContractEvidenceAvailable===true;p.commandCarrierState=c.commandCarrierState;p.framingState=c.framingState;p.correlationState=c.correlationState;p.readOnlyProbeContractReady=c.readOnlyProbeContractReady===true;p.safeReadOnlyCommandStrings=c.safeReadOnlyCommandStrings||[];p.mutatingCommandStrings=c.mutatingCommandStrings||[];p.adapterInvocationEnabled=false;p.writeOperationsLocked=true;p.destructiveOperations=false;}if(st.writeGate)st.writeGate.runtimeDexCodeContract=c;return st;}
function install(){var r=SBH.runtime,os=r.status,orf=r.refresh,orq=r.request,oas=SBH.app.start;r.status=function(){return attach(os(),cache);};r.refresh=function(){var s=orf(),c=inspect(s,false);return attach(s,c);};r.request=function(q){var c=q&&q.command?String(q.command):"",id=q&&q.requestId?String(q.requestId):"",s,d,x;if(c==="runtime.dex_code_contract"){s=orf();d=inspect(s,true);s=attach(s,d);return{ok:d.error===null&&d.dexPayloadStatus==="ok",requestId:id,code:"RUNTIME_DEX_CODE_CONTRACT",stateBefore:s.coreRunning?"running":"stopped",stateAfter:s.coreRunning?"running":"stopped",message:"Runtime DEX main 方法控制契约静态识别完成",data:d};}x=orq(q);try{s=r.status();if(x&&x.data&&s.runtimeDexCodeContract)x.data.runtimeDexCodeContract=s.runtimeDexCodeContract;}catch(e){}return x;};r.dexCodeContract=function(){return r.request({requestId:"sbh-dex-code-contract-"+SBH.util.now(),command:"runtime.dex_code_contract"});};SBH.app.start=function(){var x=oas(),s,c;try{s=r.status();c=s.runtimeDexCodeContract||empty("checking",null);x.runtimeDexCodeContract=c.state;x.runtimeDexCodeContractDetails=c;if(s.protocolAdapterPlan){x.runtimeProtocolAdapterPlan=s.protocolAdapterPlan.state;x.runtimeProtocolAdapterPlanDetails=s.protocolAdapterPlan;}}catch(e){c=empty("dex_code_contract_status_unavailable",SBH.util.errorText(e));x.runtimeDexCodeContract=c.state;x.runtimeDexCodeContractDetails=c;}x.writeOperationsLocked=true;x.destructiveOperations=false;return x;};}
if(!cache||Number(cache.schemaVersion)!==V)cache=null;else{cacheKey=String(cache.inputKey||"");cache.stale=true;cache.source="persisted_cache";}install();
}());
